name: flutter_bedrock
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2


  flutter_localizations:
    sdk: flutter
  # State
  provider: ^4.3.2+3

  #FFloat: 阿里闲鱼旗下的插件系列之一
  #墙裂！推荐阅读他们的系列文章，https://juejin.im/post/5ec17d6a5188256d7674b942#heading-12
  ffloat: ^1.0.1
  # Base Component
  # WebView iOS添加键值对 o.flutter.embedded_views_preview = YES
  #flutter 官方插件，
  #这个不会覆盖widget，但是html支持不好。
  #webview_flutter: ^0.3.19+9
  #  webview_flutter: ^0.3.21
  #这个文档齐全(支持富文本的显示：这个插件有个bug、会覆盖其它widget(不用页面切换动画是没问题的)，你用的时候更一下看看修复没有)
  #此插件为flutter社区开发，非官方，但是性能比官方号（所写时的版本），如果遇到上面所提bug
  #解决办法 参考这里：https://juejin.im/post/6864487800969003016
  flutter_webview_plugin: ^0.3.11

  #设备信息、包信息
  device_info: ^0.4.1
  package_info: ^0.4.0+6

  # 加解密
  encrypt: ^4.1.0

  # Data
  #  json_annotation: ^2.4.0
  #  dio: ^2.1.16
  dio: ^3.0.9
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.0
  path_provider: ^1.6.1
  #应用更新
  #flutter_downloader: ^1.4.4
  #install_plugin: ^2.0.1

  #shared_preferences: ^0.5.2+2
  # 本地json对象存储
  #localstorage: ^2.0.0

  # Html Encoder/Decoder
  #html_unescape: ^1.0.1+3
  # 解析html标签
  #flutter_html: ^0.11.1
  #解析富文本建议使用 markdown
  markdown_widget: ^1.1.9

  # 判断list是否相等
  collection: ^1.14.11
  #  crypto: ^2.0.6

  # UI
  oktoast: ^2.1.7

  pull_to_refresh: ^1.6.2

  #swiper
  #flutter_swiper: ^1.1.6
  #很强大的插件，瀑布流、滑动退出、手势放大等等等等，请查看文档
  #大佬的文章 https://juejin.im/post/5dee2ab36fb9a01610796a20
  #https://github.com/fluttercandies/extended_image
  extended_image: ^0.8.0
  #https://pub.dev/packages/flutter_xupdate 漂亮的更新弹窗
  #flutter_xupdate: ^0.0.3
  #刮刮卡  https://github.com/826327700/flutter_plugins_demo
  #scratcher: ^1.3.0

  #
  #  image_picker: ^0.6.5+2
  #image_picker_saver: ^0.3.0
  #image_gallery_saver: ^1.2.2
  #图片拾取
  multi_image_picker: ^4.6.6+rc.1
  #裁剪
  image_editor: ^0.1.6

  #cached_network_image: ^2.0.0-rc.1
  # 类iOS侧滑菜单
  #flutter_slidable: 0.5.3
  # 谁用谁闪亮 (骨架屏)
  shimmer: ^1.1.1
  #chart
  #mp_chart: ^0.1.9
  # 更新展示支持mark_down
  #flutter_markdown: ^0.2.0
  #flare 动画
  #flare_flutter: ^1.5.9

  # third_app
  url_launcher: ^5.1.2 #启动第三方app
  share: 0.6.2+1 #分享
  launch_review: ^2.0.0
  open_file: ^2.0.3

  # android权限弹窗
  #  permission_handler: ^3.3.0
  permission_handler: ^5.0.0+hotfix.5
  #屏幕适配
  #flutter_screenutil: ^0.5.3
  #数据库
  #sqflite: ^1.1.7
  #下方两个为常用工具类 详见文档：https://github.com/Sky24n/common_utils
  #适配、sp本地缓存、路径util等
  flustars: ^0.3.2
  #字符串util、日期格式化、加解密、日志、等等
  common_utils: ^1.2.1
  #微信 mmkv 比sp更快
  mmkv_flutter: ^1.0.10

  #网络状态
  connectivity: ^2.0.2

  #  #高德地图
  #  amap_location: ^0.2.0
  #如果你需要用到地图, 定位和搜索三个组件, 建议使用amap_all_fluttify,
  #amap_map_fluttify: ^0.21.0-dev.3
  #google_maps_flutter: ^0.5.26+4
  #location: ^3.0.2

  #bmap_map_fluttify: 0.0.2

  #抛物线动画
  #add_cart_parabola: ^0.0.6
  #banner
  carousel_slider: ^1.4.1



  #暂时使用了 ScrollablePositionedList
  #flutter_widgets: ^0.1.7+1
  #indexed_list_view: ^1.0.8

  flutter_datetime_picker: ^1.2.8

  #pop dialog  :https://juejin.im/post/5d85b4a06fb9a06af238aef9
  flutter_custom_dialog: ^1.0.19

  #微信SDK https://github.com/OpenFlutter/fluwx
  #fluwx: ^1.1.3
  #支付宝
  #tobias: ^1.2.1
  #google
  #firebase_auth: ^0.16.0
  #google_sign_in: ^4.4.1
  #facebook
  #flutter_facebook_login: ^3.0.0
  #facebook_share
  #fcm
  #firebase_messaging: ^6.0.13
  #滚动到制定item的list--- 个人经验，目前最好使的了
  scrollable_positioned_list: ^0.1.6

  #通知插件， https://pub.flutter-io.cn/packages/flutter_local_notifications
  #flutter_local_notifications: ^1.4.2
  #自定义data 滚轮选择
  #flutter_picker: ^1.1.3

  #flutter_bugly: ^0.2.8

  reflectable: ^2.2.5
  build_runner: ^1.7.0



dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_intl:
  enabled: true
